### PR TITLE
Fixes string literals

### LINKED ISSUE #84: Special characters need to be escaped
**Describe the bug**
If files has string literals it breaks the output.

### PR DESCRIPTION
**Pull request by AkimaLunar**
Escapes backticks and dollar signs in string literals. Closes #84 .

### CODE REVIEW

File: utilities/file-to-string/src/file-to-string/file-to-string.ts [hunk 1]
```diff
@@ -7,6 +7,9 @@ import type { Config, FileToStringArgs } from './file-to-string.types.js';
 const DEFAULT_OUTPUT_DIR = '__raw__';
 const DEFAULT_EXTENSION = 'ts';
 
+const escapeBackticksAndDollarSigns = (str: string) =>
+  str.replace(/[`$]/g, (match) => (match === '`' ? '\\`' : '\\$'));
```
Comment (AkimaLunar) [inline utilities/file-to-string/src/file-to-string/file-to-string.ts:11]: @brandonthomas here is the line that escapes the backtick and dollar signs.

**Review by brandonthomas — APPROVED** [review]
